sudo: "required"
dist: "trusty"
language: "generic"
services:
  - "docker"
script:
  - "export DREDD_VERSION=$(npm view dredd version)"
  - "bash build.sh"
deploy:
  provider: "script"
  script: "bash docker_push.sh"
  on:
    branch: "master"
