sudo: "required"

dist: "trusty"
language: "node_js"
services:
  - "docker"
cache:
  directories:
    - "node_modules"
install: "npm install"

script:
  - "bash build.sh"

deploy:
  provider: "script"
  script: "bash docker_push"
  on:
    branch: "master"
